server.port=8082
spring.application.name=claims-service

# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/claimsdb
#local setting
services.policy-service.url=http://localhost:8081/api/policies